In [1]:
import numpy as np

In [2]:
a = []
for i in range(10):
    a.append(i)

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
arr = np.array([1,2,3,4,5])
print(arr.shape)

(5,)


In [8]:
arr = np.array([[1,2,3]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(1, 3)

In [11]:
arr = np.array([[1], 
                [2], 
                [3]])

In [12]:
arr.shape

(3, 1)

In [13]:
arr = np.array([[1,2],
                [1,2],
                [1,2]])

In [14]:
arr.shape

(3, 2)

In [15]:
x = np.array([[1,2,3], 
              [1,2,3], 
              [1,2,3]])

y = np.array([[4,5,6], 
              [4,5,6], 
              [4,5,6]])

In [34]:
print(x + y, '\n', np.add(x, y), '\n', np.subtract(x, y))

[[5 7 9]
 [5 7 9]
 [5 7 9]] 
 [[5 7 9]
 [5 7 9]
 [5 7 9]] 
 [[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]


In [33]:
print(np.sum(x, axis = 0))

[3 6 9]


In [37]:
print(x / y, '\n', np.divide(x, y))

[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]] 
 [[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]


In [43]:
print(x * y, '\n', x@y, '\n', np.multiply(x, y), '\n', np.matmul(x, y))

[[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]] 
 [[24 30 36]
 [24 30 36]
 [24 30 36]] 
 [[ 4 10 18]
 [ 4 10 18]
 [ 4 10 18]] 
 [[24 30 36]
 [24 30 36]
 [24 30 36]]


In [45]:
arr = np.array([1,2,3])
print(np.dot(arr, arr))

14


In [52]:
print(np.full((3, 2), 10))

[[10 10]
 [10 10]
 [10 10]]


In [55]:
np.zeros((3, 2)), np.ones((3, 2))

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.arange(10, 25, 3)

array([10, 13, 16, 19, 22])

In [71]:
np.linspace(10, 101, 5)

array([ 10.  ,  32.75,  55.5 ,  78.25, 101.  ])

In [72]:
print(x, '\n', y)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 
 [[4 5 6]
 [4 5 6]
 [4 5 6]]


In [82]:
x = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

y = np.array([[10,11,12], 
              [13,14,15], 
              [16,17,18]])

In [87]:
np.stack((x, y), axis = 2)

array([[[ 1, 10],
        [ 2, 11],
        [ 3, 12]],

       [[ 4, 13],
        [ 5, 14],
        [ 6, 15]],

       [[ 7, 16],
        [ 8, 17],
        [ 9, 18]]])

In [106]:
one = np.ones((3, 1), dtype = 'int64')

In [104]:
one

array([[1],
       [1],
       [1]], dtype=int64)

In [107]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
x = np.hstack((one, x))

In [118]:
np.mean(x, axis = 0)

array([1., 4., 5., 6.])

In [121]:
np.std(x, axis = 0)

array([0.        , 2.44948974, 2.44948974, 2.44948974])

In [132]:
np.random.randint(10, 20, (2, 6))

array([[14, 13, 19, 10, 18, 10],
       [10, 19, 15, 16, 13, 12]])

In [135]:
np.random.rand(2, 3)

array([[0.05891086, 0.08326966, 0.2069152 ],
       [0.51992003, 0.72572657, 0.493984  ]])

In [138]:
np.random.randn(2, 4)

array([[ 0.49674668, -1.01585775, -0.70370674, -1.45713273],
       [-0.05148068, -0.08767007,  2.11405706,  0.76683323]])

In [145]:
np.random.random()

0.06936012378142509

In [146]:
np.random.random_sample?

In [147]:
x

array([[1, 1, 2, 3],
       [1, 4, 5, 6],
       [1, 7, 8, 9]], dtype=int64)

In [153]:
x[0]

array([1, 1, 2, 3], dtype=int64)